  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/project/modules/web-ui" # MUST BE UPDATED UPON TYPESCRIPT PROGRAMMING
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC
      time: "09:00"
      timezone: "America/Los_Angeles"
    target-branch: "master"
    versioning-strategy: auto

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/project/modules/orchestration"
    # Check for updates once a week
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC
      time: "09:00"
      timezone: "America/Los_Angeles"
    target-branch: "master"