# Use the latest TensorFlow Docker image as the base image
FROM tensorflow/tensorflow:latest

# Set the working directory in the container
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy the preprocessor Python script into the container
COPY preprocessor.py /app/preprocessor.py

# Install the required Python libraries
RUN pip install --no-cache-dir numpy PyPDF2 scikit-learn

# Define the entrypoint script
ENTRYPOINT ["python", "/app/preprocessor.py"]
