version: '3.8'

services:
  proxy:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data-volume:/app/data
    networks:
      - backend-network
    environment:
      - OUTPUT_FILE_PATH=/app/data/output.csv
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  data-volume:
